from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from factor_intelligence_utils import utc_iso


VALID_DIRECTIONS = {"higher_is_better", "lower_is_better", "neutral", "contextual"}
VALID_CATEGORIES = {
    "momentum",
    "trend",
    "volatility",
    "liquidity",
    "quality",
    "valuation",
    "sentiment",
    "revisions",
    "regime",
    "technical",
    "fundamental",
    "custom",
}


@dataclass(frozen=True)
class FactorDefinition:
    factor_id: str
    name: str
    description: str
    category: str
    version: str
    direction: str
    calculation_source: str
    lookback_period: int | None
    minimum_history_required: int | None
    expected_value_type: str = "numeric"
    active: bool = True
    created_at: str = field(default_factory=utc_iso)
    metadata: dict[str, Any] = field(default_factory=dict)


class FactorRegistry:
    def __init__(self):
        self._factors: dict[tuple[str, str], FactorDefinition] = {}

    def register(self, definition: FactorDefinition) -> None:
        factor_id = definition.factor_id.strip()
        version = definition.version.strip()
        if not factor_id:
            raise ValueError("factor_id is required")
        if not version:
            raise ValueError("version is required")
        if definition.direction not in VALID_DIRECTIONS:
            raise ValueError(f"invalid direction: {definition.direction}")
        if definition.category not in VALID_CATEGORIES:
            raise ValueError(f"invalid category: {definition.category}")
        key = (factor_id, version)
        if key in self._factors:
            raise ValueError(f"duplicate factor registration: {factor_id}:{version}")
        self._factors[key] = definition

    def register_many(self, definitions: list[FactorDefinition]) -> None:
        for definition in definitions:
            self.register(definition)

    def get(self, factor_id: str, version: str | None = None) -> FactorDefinition:
        if version is not None:
            key = (factor_id, version)
            if key not in self._factors:
                raise KeyError(f"unknown factor: {factor_id}:{version}")
            return self._factors[key]
        matches = [value for key, value in self._factors.items() if key[0] == factor_id]
        if not matches:
            raise KeyError(f"unknown factor: {factor_id}")
        matches.sort(key=lambda item: item.version)
        return matches[-1]

    def list_factors(self, active_only: bool = False, category: str | None = None) -> list[FactorDefinition]:
        items = list(self._factors.values())
        if active_only:
            items = [item for item in items if item.active]
        if category is not None:
            items = [item for item in items if item.category == category]
        return sorted(items, key=lambda item: (item.factor_id, item.version))


def default_factor_definitions() -> list[FactorDefinition]:
    return [
        FactorDefinition(
            factor_id="overall_score",
            name="Overall Score",
            description="Composite scanner score from Sprint 2-9 factor engine.",
            category="quality",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.overall_score",
            lookback_period=None,
            minimum_history_required=1,
            metadata={"field": "overall_score"},
        ),
        FactorDefinition(
            factor_id="confidence",
            name="Confidence",
            description="Scanner confidence level.",
            category="quality",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.confidence",
            lookback_period=None,
            minimum_history_required=1,
            metadata={"field": "confidence"},
        ),
        FactorDefinition(
            factor_id="trend_score",
            name="Trend",
            description="Trend factor score generated by factor engine.",
            category="trend",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.trend_score",
            lookback_period=200,
            minimum_history_required=200,
            metadata={"field": "trend_score"},
        ),
        FactorDefinition(
            factor_id="momentum_score",
            name="Momentum",
            description="Momentum factor score generated by factor engine.",
            category="momentum",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.momentum_score",
            lookback_period=26,
            minimum_history_required=26,
            metadata={"field": "momentum_score"},
        ),
        FactorDefinition(
            factor_id="volume_score",
            name="Volume",
            description="Volume confirmation score.",
            category="liquidity",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.volume_score",
            lookback_period=20,
            minimum_history_required=20,
            metadata={"field": "volume_score"},
        ),
        FactorDefinition(
            factor_id="volatility_score",
            name="Volatility",
            description="Volatility-adjusted score from factor engine.",
            category="volatility",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.volatility_score",
            lookback_period=20,
            minimum_history_required=20,
            metadata={"field": "volatility_score"},
        ),
        FactorDefinition(
            factor_id="liquidity_score",
            name="Liquidity",
            description="Liquidity score from scanner.",
            category="liquidity",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.liquidity_score",
            lookback_period=20,
            minimum_history_required=20,
            metadata={"field": "liquidity_score"},
        ),
        FactorDefinition(
            factor_id="market_regime_score",
            name="Market Regime Score",
            description="Regime alignment score from factor engine.",
            category="regime",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.market_regime_score",
            lookback_period=None,
            minimum_history_required=1,
            metadata={"field": "market_regime_score"},
        ),
        FactorDefinition(
            factor_id="risk_quality_score",
            name="Risk Quality",
            description="Risk quality score from factor engine.",
            category="quality",
            version="v1",
            direction="higher_is_better",
            calculation_source="research_candidates.risk_quality_score",
            lookback_period=None,
            minimum_history_required=1,
            metadata={"field": "risk_quality_score"},
        ),
        FactorDefinition(
            factor_id="rank",
            name="Scanner Rank",
            description="Candidate rank where smaller values are better.",
            category="custom",
            version="v1",
            direction="lower_is_better",
            calculation_source="research_candidates.rank",
            lookback_period=None,
            minimum_history_required=1,
            metadata={"field": "rank"},
        ),
    ]


def build_default_registry() -> FactorRegistry:
    registry = FactorRegistry()
    registry.register_many(default_factor_definitions())
    return registry
